//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_additional
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int additional_id { get; set; }
        public Nullable<int> additional_id2 { get; set; }
        public Nullable<int> additional_id3 { get; set; }
    
        public virtual additional_list additional_list { get; set; }
        public virtual additional_list additional_list1 { get; set; }
        public virtual additional_list additional_list2 { get; set; }
        public virtual orders orders { get; set; }
    }
}
