//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authtorizations
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
