//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class construction_organizationEntities1 : DbContext
    {
        public construction_organizationEntities1()
            : base("name=construction_organizationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<active_additional> active_additional { get; set; }
        public virtual DbSet<additional_list> additional_list { get; set; }
        public virtual DbSet<Authtorizations> Authtorizations { get; set; }
        public virtual DbSet<order_payments> order_payments { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<orders_history> orders_history { get; set; }
        public virtual DbSet<payment_types> payment_types { get; set; }
        public virtual DbSet<receipts> receipts { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
