//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_history
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public bool completed { get; set; }
        public bool canceled { get; set; }
        public bool paused { get; set; }
        public bool paid { get; set; }
        public string reason { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
