//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_payments
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int payment_type { get; set; }
        public bool paid { get; set; }
        public string bank { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual payment_types payment_types { get; set; }
    }
}
