//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipts
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public Nullable<long> sum { get; set; }
        public string note { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
