//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronimyc { get; set; }
        public int role { get; set; }
        public int passport_num { get; set; }
        public int inn_num { get; set; }
        public bool at_site { get; set; }
        public Nullable<int> account { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
